<section class="cadastro">
    <form action="/cadastrar" method="post" class="formulario-cadastro">
        <input type="text" name="name" placeholder="nome" required>
        <input type="text" name="email" placeholder="email" required>
        <input type="password" name="password" placeholder="senha" required>
        <input type="submit" value="Cadastrar" class="btn-formulario">
    </form>

    <p>Já possui cadastro? Faça login  <a href="/login"> aqui.</a></p>
</section>