<?
    if(isset($_SESSION['username'])){
        echo  $_SESSION['username'];
    }

?>

<title>principal</title>

<section class="todos-os-posts">
    <section class="posts">

        <?php foreach($this->view->posts as $idx => $post){?>
            <div class="post">
                <div class="post-image-titulo">
                    <a href="/post?id=<?= $post['id_post']?>">
                        <img class="post-image" src="<?= $post['image_post']?>" alt="foto">
                    </a>
                    <div>
                        <a href="/post?id=<?= $post['id_post']?>" class="titulo-post"><?= $post['title_post']?></a>
                        <small><?= $post['date_post']?></small>
                        <small><?= $post['author']?></small>/
                        <small><?= $post['category']?></small>
                    </div>
                </div>
                <div class="post-texto">
                    <p><?= $post['description']?></p>
                </div>
            </div>
        <?}?>
    </section>
    
    <aside class="favoritos">

        <?php foreach($this->view->favoritePosts as $idx => $post){?>
            <div class="favoritos-post">
                <div>
                    <a href="/post?id=<?= $post['id_post']?>" class="imagem-lateral">
                        <img src="<?= $post['image_post'] ?>" alt="foto">
                    </a>  
                    <a href="/post?id=<?= $post['id_post']?>" class="titulo-lateral"><?= $post['title_post'] ?></a>
                </div>
                <div class="favoritos-texto-post">
                    <p><?= $post['description'] ?></p>
                </div>
            </div>
        <?}?>
        
        <h2>#Siga-nos</h2>
    </aside>
</section>