<?
    if(isset($_SESSION['username'])){
        echo  $_SESSION['username'];
    }

    // posts
    // echo '<pre>';
    // print_r($this->view->posts);
    // echo '</pre>';

    //favorites
    echo '<pre>';
    print_r($this->view->favoritePosts);
    echo '</pre>';
?>

<title>principal</title>

<section class="todos-os-posts">
    <section class="posts">
        <div class="post">
            <a href="/post?nome=thalisson&sobrenome=medeiros" class="post-imagem">
                <img src="imagens/foto2.png" alt="foto">
            </a>
            <article class="post-conteudo">
                <a href="#" class="titulo-post">titulo</a>
                <span>20/20/2020</span>
                <span>alguem</span>
                .
                <span>esporte</span>
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae 
                </p>
            </article>
        </div>
    </section>
    
    <aside class="favoritos">
        <div class="favoritos-post">
            <div>
                <a href="#" class="imagem-lateral">
                    <img src="imagens/foto2.png" alt="foto">
                </a>  
                <a href="#" class="titulo-lateral">um titulo maior o possivel</a>
            </div>
            <p>
                blanditiis mollitia expedita,
                illum quibusdam maxime aliquid repellat delectus? 
            </p>
        </div>
        <div class="favoritos-post">
            <div>
                <a href="#" class="imagem-lateral">
                    <img src="imagens/foto2.png" alt="foto">
                </a>  
                <a href="#" class="titulo-lateral">um titulo maior o possivel</a>
            </div>
            <p>
                blanditiis mollitia expedita,
                illum quibusdam maxime aliquid repellat delectus? 
            </p>
        </div>
        <div class="favoritos-post">
            <div>
                <a href="#" class="imagem-lateral">
                    <img src="imagens/foto2.png" alt="foto">
                </a>  
                <a href="#" class="titulo-lateral">um titulo maior o possivel</a>
            </div>
            <p>
                blanditiis mollitia expedita,
                illum quibusdam maxime aliquid repellat delectus? 
            </p>
        </div>
        <h2>#Siga-nos</h2>
    </aside>
</section>