<?php
    
    // echo '<pre>';
    // print_r($this->view->comments);
    // echo '</pre>';

    // echo '<pre>';
    // print_r($this->view->nameUsers);
    // echo '</pre>';

?>

<h1><?=$this->view->onePost['title_post']?></h1>

<div class="post-unico-titulo">
    <span><?=$this->view->onePost['date_post']?></span>
    <span><?=$this->view->onePost['author']?></span>
    <span><?=$this->view->onePost['category']?></span>
</div>

<section class="post-unico-conteudo">
    <div class="imagem">
        <img src="<?=$this->view->onePost['image_post']?>" alt="foto">
    </div>
    <p><?=$this->view->onePost['description']?></p>
</section>

<div class="subtitulo">
    <h2>Posts relacionados</h2>
</div>

<section class="posts-relacionados">
    <a href="#" class="imagem-posts-relacionados">
        <img src="<?=$this->view->onePost['image_post']?>" alt="foto">
        <h2 class="posts-relacionados-titulo ">titulo</h2>
    </a>

    <a href="#" class="imagem-posts-relacionados">
        <img src="<?=$this->view->onePost['image_post']?>" alt="foto">
        <h2 class="posts-relacionados-titulo ">titulo</h2>
    </a>

    <a href="#" class="imagem-posts-relacionados">
        <img src="<?=$this->view->onePost['image_post']?>" alt="foto">
        <h2 class="posts-relacionados-titulo ">titulo</h2>
    </a>
</section>

<div class="subtitulo">
    <h2>Comentários</h2>
</div>

<section class="comentarios">
    <h2><span class="quantidade-comentarios"><?=$this->view->comments['qtd_comments']?></span>Comentários:</h2>

    <form action="/comentar" method="post">
        
        <input type="hidden" name="id_post" value="<?= $this->view->onePost['id_post'] ?>">

        <? if(isset($_SESSION['id'])) { ?>
            <input type="hidden" name="name" value="<?= $_SESSION['username'] ?>">
            <input type="hidden" name="id_user" value="<?= $_SESSION['id'] ?>">
        <? } ?>

        <textarea name="comment" class="texto-comentario" placeholder="Comentar..."></textarea>
        
        <?if(isset($_SESSION['username'])){ ?> 
            <input type="submit" class="btn-comentar" value="comentar">    
        <? } else{ ?>
            <a href="/login" class="btn-cadastrar">Faça login para poder comentar</a> 
        <? } ?>
    </form>

    <section class="comentarios-usuarios">
        <?foreach($this->view->nameUsers as $idx => $value){?>
            <small><?= $value['name'] ?> Comentou:</small>
            <textarea class="texto-comentario-usuario" readonly placeholder="<?= $value['comment'] ?>"></textarea>
        <?}?>
    </section>
</section>