<link rel="stylesheet" href="../css/post-unico.css">

<h1>titulo</h1>

<div class="post-unico-titulo">
    <span>20/20/2020</span>
    <span>alguem</span>
    <span>Esporte</span>
</div>

<section class="post-unico-conteudo">
    <div class="imagem">
        <img src="foto2.png" alt="foto">
    </div>
    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore 
        mollitia quisquam exercitationem quas excepturi non fugiat, nihil, 
        illo esse doloribus amet? Cum odit commodi provident aperiam? 
        Repellendus tempora minus itaque.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        Unde doloremque, modi quidem fuga ratione possimus similique 
        tenetur soluta sit dicta fugiat sequi alias iure temporibus 
        vero optio natus laboriosam voluptatum. 
    </p>
</section>

<div class="subtitulo">
    <h2>Posts relacionados</h2>
</div>

<section class="posts-relacionados">
    <a href="#" class="imagem-posts-relacionados">
        <img src="foto2.png" alt="foto">
        <h2 class="posts-relacionados-titulo ">titulo</h2>
    </a>

    <a href="#" class="imagem-posts-relacionados">
        <img src="foto2.png" alt="foto">
        <h2 class="posts-relacionados-titulo ">titulo</h2>
    </a>

    <a href="#" class="imagem-posts-relacionados">
        <img src="foto2.png" alt="foto">
        <h2 class="posts-relacionados-titulo ">titulo</h2>
    </a>
</section>

<div class="subtitulo">
    <h2>Comentários</h2>
</div>

<section class="comentarios">
    <h2><span class="quantidade-comentarios">0</span>Comentários:</h2>

    <!-- aqui fazer uma verificação. se o usuario for cadastrado mostrar a caixa de texto
         senão mostrar o botão de cadastro. -->
    <div>
        <textarea name="comentario" class="texto-comentario" placeholder="Comentar..."></textarea>
    </div>

    <button class="btn-comentar">Comentar</button>
    <a href="/cadastro" class="btn-cadastrar">Faça login para poder comentar</a>
</section>