<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="assets/css/index.css">
    <link rel="stylesheet" href="assets/css/menu.css">
    <link rel="stylesheet" href="assets/css/footer.css">
    <link rel="stylesheet" href="assets/css/post-unico.css">
    <link rel="stylesheet" href="assets/css/cadastro.css">
    <link rel="stylesheet" href="assets/css/login.css">
</head>
<body>
    <nav class="menu">
        <section class="social">
            <ul>
                <li>
                    <a href="facebook">
                        <i class="fa-brands fa-square-facebook"></i>
                    </a>
                </li>
                <li>
                    <a href="youtube">  
                        <i class="fa-brands fa-youtube"></i>
                    </a>
                </li>
                <li>
                    <a href="X">        
                        <i class="fa-brands fa-x-twitter"></i>
                    </a>
                </li>
                <li>
                    <a href="pinterest">
                        <i class="fa-brands fa-pinterest"></i>
                    </a>
                </li>
                <li>
                    <a href="/sair">Sair
                        <i class="fa-solid fa-person-running"></i>
                    </a>
                </li>
            </ul>
        </section>

        <div class="titulo">
            <a href="/">Blog</a>
        </div>

        <section class="menu-items">
            <ul>
                <li><a href="/"><i class="fa-solid fa-house"></i></a></li>
                <li><a href="Esporte">Esporte</a></li>
                <li><a href="lazer">lazer</a></li>
                <li><a href="automoveis">automoveis</a></li>
                <li><a href="curiosidades">curiosidades</a></li>
            </ul>
        </section>

        <div class="icones-menu-escondido">
            <a href="/" class="menu-escondido-btn"><i class="fa-solid fa-house"></i></a>
            <button class="menu-escondido-btn" onclick="exibirMenu()"><i class="fa-solid fa-bars"></i></button>
        </div>

        <section class="menu-escondido">
            <ul>
                <li><a class="menu-escondido-btn" href="Esporte">Esporte</a></li>
                <li><a class="menu-escondido-btn" href="lazer">lazer</a></li>
                <li><a class="menu-escondido-btn" href="automoveis">automoveis</a></li>
                <li><a class="menu-escondido-btn" href="curiosidades">curiosidades</a></li>
            </ul>
        </section>
    </nav>

    <?php $this->content(); ?>

    <footer>
        <section class="social-footer">
            <ul>
                <li>
                    <a class="footer-btn" href="facebook">
                        <i class="fa-brands fa-square-facebook"></i>
                    </a>
                </li>
                <li>
                    <a class="footer-btn" href="youtube">  
                        <i class="fa-brands fa-youtube"></i>
                    </a>
                </li>
                <li>
                    <a class="footer-btn" href="X">        
                        <i class="fa-brands fa-x-twitter"></i>
                    </a>
                </li>
                <li>
                    <a class="footer-btn" href="pinterest">
                        <i class="fa-brands fa-pinterest"></i>
                    </a>
                </li>
            </ul>

            <p>Criado por Tam&copy;</p>

            <small>2024</small>
        </section> 
    </footer>

    <script src="assets/js/index.js"></script>
</body>
</html>